import Head from "next/head";
import AboutSection from "../components/AboutSection";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Header from "../components/Header";
import ImageRow from "../components/ImageRow";
import Verticals from "../components/Verticals";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Verticals />
      <ImageRow
        position={"left"}
        header="Government Services."
        img={{
          src: "https://empirelodging.com/wp-content/uploads/2021/04/GovernmentServicesSecondary.jpg",
          alt: "Soldier looking towards US Flag",
        }}
      >
        <p>
          Support for the United States Military including MEPS, National Guard,
          VA, US Coast Guard, US Navy, and more. &nbsp;Empire is a GSA contract
          holder providing high quality lodging, transport, and meals for
          government programs and employees across the country.
        </p>
        <p>
          Our experienced team offers quality assurance inspections, accurate
          and concise accounting, prompt and clear communication, with full
          contract management services.&nbsp; We are proud to serve those who
          serve us!
        </p>
      </ImageRow>
      <ImageRow
        position={"right"}
        header="Corporate Housing"
        img={{
          src: "https://empirelodging.com/wp-content/uploads/2021/04/CorporateHousingSecondary.jpg",
          alt: "Soldier looking towards US Flag",
        }}
      >
        <p>
          Quality, affordable, long and short-term housing for all industries
          including business travelers, construction crews, traveling nurses,
          and government employees. Relocation made easy with all-inclusive
          rent, utility and furnishing packages tailored to your specific needs.
        </p>
        <p>
          Corporate travel is hard enough. Leave the logistics to us! We have
          access to an extensive network of apartments and hotels throughout the
          United States, which allows us to find just the right housing for you
          and your team.
        </p>
      </ImageRow>
      <ImageRow
        position={"left"}
        header="Emergency Lodging"
        img={{
          src: "https://empirelodging.com/wp-content/uploads/2021/04/EmergencyLodgingSecondary.jpg",
          alt: "Soldier looking towards US Flag",
        }}
      >
        <p>
          Immediate lodging for utility outages and disaster relief. We source
          bulk hotel rooms and work directly with hotels to maintain ongoing
          bookings. Full accounting services and consolidated invoicing allow
          you to focus on getting people back in their homes.
        </p>
        <p>
          You have housing requirements that need to be met quickly and at the
          right price; Empire has the deep industry knowledge and unparalleled
          experience to supply and manage emergency accommodation while giving
          you some much needed peace of mind.
        </p>
      </ImageRow>
      <ImageRow
        position={"right"}
        header="Business Travel"
        img={{
          src: "https://empirelodging.com/wp-content/uploads/2021/04/BusinessTravelSecondary.jpg",
          alt: "Soldier looking towards US Flag",
        }}
      >
        <p>
          A comprehensive travel program that simplifies initiatives from
          reservations and reporting to account reviews. Our experienced team
          has developed a travel program that will deliver results and improve
          your cost savings.
        </p>
        <p>
          Utilizing proprietary software and strong relationships with our
          national hotel partners, Empire does the heavy lifting to ensure your
          travel goals and budgets are met.
        </p>
      </ImageRow>
      <ImageRow
        position={"left"}
        header="Team Travel"
        img={{
          src: "https://empirelodging.com/wp-content/uploads/2021/11/AdobeStock_289511278-1-scaled.jpeg",
          alt: "Soldier looking towards US Flag",
        }}
      >
        <p>
          Traveling with a Team? Our hospitality experts (& sports fanatics)
          source hotels with the amenities you need, and provide concessions
          that matter to you. Our services include a custom booking platform,
          room block management, negotiated discounts and attention to detail so
          you can Play Hard and Plan Easy!
        </p>
      </ImageRow>
      <AboutSection />
      <Contact />
      <Footer />
    </div>
  );
}
